### ISSUE TITLE
Incorrect Type for options param

### ISSUE THREAD

**Issue by onx2** [pocesar/react-use-event-listener#1]
I think this line https://github.com/pocesar/react-use-event-listener/blob/master/src/index.ts#L20 should actually be `options?: AddEventListenerOptions` so it can accept `once` and `passive`.

I can make this change if you agree 😄

**Comment by pocesar** [comment]
thanks @onx2, that is indeed correct, I'll merge the PR if you send one

**Comment by pocesar** [comment]
merged
